#IF YOU BREAK IT YOU BOUGHT IT

runtime: go
api_version: go1
env: flex
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: /favicon\.ico
- url: /.*
  script: _go_app



env_variables:
  # See https://godoc.org/github.com/lib/pq
  #
  # Replace INSTANCE_CONNECTION_NAME with the same value as in the
  # beta_settings section below.
  POSTGRES_CONNECTION: "user=postgres password=password dbname=sdev_db host=/cloudsql/co-lab-237404:us-central1:co-lab-db"
  #
  # If you're testing locally using the Cloud SQL proxy with TCP,
  # instead set this environment variable:
  # POSTGRES_CONNECTION="user=postgres password=pw dbname=db sslmode=disable"

beta_settings:
  cloud_sql_instances: "co-lab-237404:us-central1:co-lab-db"
